// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/pvz-handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	forms "pvz/internal/delivery/forms"
	models "pvz/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPvzUseCase is a mock of PvzUseCase interface.
type MockPvzUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPvzUseCaseMockRecorder
}

// MockPvzUseCaseMockRecorder is the mock recorder for MockPvzUseCase.
type MockPvzUseCaseMockRecorder struct {
	mock *MockPvzUseCase
}

// NewMockPvzUseCase creates a new mock instance.
func NewMockPvzUseCase(ctrl *gomock.Controller) *MockPvzUseCase {
	mock := &MockPvzUseCase{ctrl: ctrl}
	mock.recorder = &MockPvzUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPvzUseCase) EXPECT() *MockPvzUseCaseMockRecorder {
	return m.recorder
}

// CreatePvz mocks base method.
func (m *MockPvzUseCase) CreatePvz(ctx context.Context, pvzForm forms.PvzForm) (models.Pvz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePvz", ctx, pvzForm)
	ret0, _ := ret[0].(models.Pvz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePvz indicates an expected call of CreatePvz.
func (mr *MockPvzUseCaseMockRecorder) CreatePvz(ctx, pvzForm interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePvz", reflect.TypeOf((*MockPvzUseCase)(nil).CreatePvz), ctx, pvzForm)
}

// GetPvzInfo mocks base method.
func (m *MockPvzUseCase) GetPvzInfo(ctx context.Context, form forms.GetPvzInfoForm) ([]models.PvzInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPvzInfo", ctx, form)
	ret0, _ := ret[0].([]models.PvzInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPvzInfo indicates an expected call of GetPvzInfo.
func (mr *MockPvzUseCaseMockRecorder) GetPvzInfo(ctx, form interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPvzInfo", reflect.TypeOf((*MockPvzUseCase)(nil).GetPvzInfo), ctx, form)
}
